-- V1: 초기 스키마 생성
-- 실행 날짜: 2025-02-13

-- Sample Table
CREATE TABLE IF NOT EXISTS TB_SAMPLE (
    SAMPLE_ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT,
    USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
    REG_USER_ID VARCHAR(50),
    REG_DATETIME TIMESTAMP,
    UPDATER_ID VARCHAR(50),
    UPDATE_DATETIME TIMESTAMP
);

-- 테이블 코멘트
COMMENT ON TABLE TB_SAMPLE IS '샘플 테이블';
COMMENT ON COLUMN TB_SAMPLE.SAMPLE_ID IS '샘플_ID';
COMMENT ON COLUMN TB_SAMPLE.TITLE IS '제목';
COMMENT ON COLUMN TB_SAMPLE.CONTENT IS '내용';
COMMENT ON COLUMN TB_SAMPLE.USE_YN IS '사용_여부';
COMMENT ON COLUMN TB_SAMPLE.REG_USER_ID IS '등록자_ID';
COMMENT ON COLUMN TB_SAMPLE.REG_DATETIME IS '등록_일시';
COMMENT ON COLUMN TB_SAMPLE.UPDATER_ID IS '수정자_ID';
COMMENT ON COLUMN TB_SAMPLE.UPDATE_DATETIME IS '수정_일시';

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_tb_sample_use_yn ON TB_SAMPLE(USE_YN);
CREATE INDEX IF NOT EXISTS idx_tb_sample_reg_datetime ON TB_SAMPLE(REG_DATETIME);
