-- 메일 발송 이력 테이블 생성
CREATE TABLE TB_MAIL_HISTORY (
    MAIL_HISTORY_ID BIGSERIAL PRIMARY KEY,
    SUBJECT VARCHAR(500) NOT NULL,
    CONTENT TEXT NOT NULL,
    TO_ADDRESS VARCHAR(500) NOT NULL,
    CC VARCHAR(1000),
    BCC VARCHAR(1000),
    IS_HTML BOOLEAN NOT NULL DEFAULT FALSE,
    STATUS VARCHAR(20) NOT NULL,
    ERROR_MESSAGE TEXT,
    SENT_AT TIMESTAMP NOT NULL,
    REG_USER_ID VARCHAR(50),
    REG_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID VARCHAR(50),
    UPDATE_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX idx_mail_history_status ON TB_MAIL_HISTORY(STATUS);
CREATE INDEX idx_mail_history_sent_at ON TB_MAIL_HISTORY(SENT_AT);
CREATE INDEX idx_mail_history_to_address ON TB_MAIL_HISTORY(TO_ADDRESS);

-- 테이블 코멘트
COMMENT ON TABLE TB_MAIL_HISTORY IS '메일 발송 이력';
COMMENT ON COLUMN TB_MAIL_HISTORY.MAIL_HISTORY_ID IS '메일 이력 ID';
COMMENT ON COLUMN TB_MAIL_HISTORY.SUBJECT IS '메일 제목';
COMMENT ON COLUMN TB_MAIL_HISTORY.CONTENT IS '메일 내용';
COMMENT ON COLUMN TB_MAIL_HISTORY.TO_ADDRESS IS '수신자 이메일';
COMMENT ON COLUMN TB_MAIL_HISTORY.CC IS '참조 이메일 (콤마 구분)';
COMMENT ON COLUMN TB_MAIL_HISTORY.BCC IS '숨은 참조 이메일 (콤마 구분)';
COMMENT ON COLUMN TB_MAIL_HISTORY.IS_HTML IS 'HTML 여부';
COMMENT ON COLUMN TB_MAIL_HISTORY.STATUS IS '발송 상태 (SUCCESS, FAILED)';
COMMENT ON COLUMN TB_MAIL_HISTORY.ERROR_MESSAGE IS '에러 메시지 (실패 시)';
COMMENT ON COLUMN TB_MAIL_HISTORY.SENT_AT IS '발송 시도 시각';
COMMENT ON COLUMN TB_MAIL_HISTORY.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN TB_MAIL_HISTORY.REG_DATETIME IS '등록일시';
COMMENT ON COLUMN TB_MAIL_HISTORY.UPDATER_ID IS '수정자 ID';
COMMENT ON COLUMN TB_MAIL_HISTORY.UPDATE_DATETIME IS '수정일시';
