-- 사용자 테이블 생성
CREATE TABLE TB_USER
(
    USER_ID              BIGSERIAL PRIMARY KEY,
    USERNAME             VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD             VARCHAR(100) NOT NULL,
    USER_NAME            VARCHAR(100),
    EMAIL                VARCHAR(100),
    ROLE                 VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    ENABLED              BOOLEAN      NOT NULL DEFAULT TRUE,
    ACCOUNT_NON_LOCKED   BOOLEAN      NOT NULL DEFAULT TRUE,
    LAST_LOGIN_AT        TIMESTAMP,
    CREATED_DATE         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY           VARCHAR(255),
    LAST_MODIFIED_DATE   TIMESTAMP,
    LAST_MODIFIED_BY     VARCHAR(255)
);

-- 인덱스 생성
CREATE INDEX idx_user_username ON TB_USER (USERNAME);
CREATE INDEX idx_user_email ON TB_USER (EMAIL);

-- 테이블 코멘트
COMMENT ON TABLE TB_USER IS '사용자 테이블';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자_ID';
COMMENT ON COLUMN TB_USER.USERNAME IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN TB_USER.EMAIL IS '이메일';
COMMENT ON COLUMN TB_USER.ROLE IS '권한 (ROLE_USER, ROLE_ADMIN)';
COMMENT ON COLUMN TB_USER.ENABLED IS '계정 활성화 여부';
COMMENT ON COLUMN TB_USER.ACCOUNT_NON_LOCKED IS '계정 잠금 여부';
COMMENT ON COLUMN TB_USER.LAST_LOGIN_AT IS '최종 로그인 일시';
COMMENT ON COLUMN TB_USER.CREATED_DATE IS '생성일시';
COMMENT ON COLUMN TB_USER.CREATED_BY IS '생성자';
COMMENT ON COLUMN TB_USER.LAST_MODIFIED_DATE IS '수정일시';
COMMENT ON COLUMN TB_USER.LAST_MODIFIED_BY IS '수정자';

-- 테스트용 기본 사용자 추가 (비밀번호: password, BCrypt 암호화)
-- BCrypt로 'password'를 암호화한 값: $2a$10$K8yN/YvPjLEqVvWm9bGTy.CZvbVHpXR0c8OZr8Kc/W/pZL.mFxU3i
INSERT INTO TB_USER (USERNAME, PASSWORD, USER_NAME, EMAIL, ROLE, ENABLED, ACCOUNT_NON_LOCKED)
VALUES ('admin', '$2a$10$K8yN/YvPjLEqVvWm9bGTy.CZvbVHpXR0c8OZr8Kc/W/pZL.mFxU3i', '관리자', 'admin@example.com', 'ROLE_ADMIN', TRUE, TRUE),
       ('user', '$2a$10$K8yN/YvPjLEqVvWm9bGTy.CZvbVHpXR0c8OZr8Kc/W/pZL.mFxU3i', '일반사용자', 'user@example.com', 'ROLE_USER', TRUE, TRUE);
