-- 다국어 그룹 테이블
CREATE TABLE IF NOT EXISTS TB_MLG_GROUP (
    MLG_CODE_VAL    VARCHAR(10)     NOT NULL,
    USE_YN          BOOLEAN         NOT NULL DEFAULT TRUE,
    REMARK_CONTENT  VARCHAR(500),
    REG_USER_ID     VARCHAR(50),
    REG_DATETIME    TIMESTAMP,
    UPDATER_ID      VARCHAR(50),
    UPDATE_DATETIME TIMESTAMP,
    CONSTRAINT PK_MLG_GROUP PRIMARY KEY (MLG_CODE_VAL)
);

COMMENT ON TABLE TB_MLG_GROUP IS '다국어 그룹';
COMMENT ON COLUMN TB_MLG_GROUP.MLG_CODE_VAL IS '다국어 코드값';
COMMENT ON COLUMN TB_MLG_GROUP.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_MLG_GROUP.REMARK_CONTENT IS '비고';
COMMENT ON COLUMN TB_MLG_GROUP.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN TB_MLG_GROUP.REG_DATETIME IS '등록 일시';
COMMENT ON COLUMN TB_MLG_GROUP.UPDATER_ID IS '수정자 ID';
COMMENT ON COLUMN TB_MLG_GROUP.UPDATE_DATETIME IS '수정 일시';

-- 다국어 상세 테이블
CREATE TABLE IF NOT EXISTS TB_MLG_DETAIL (
    MLG_DETAIL_ID   BIGSERIAL       NOT NULL,
    MLG_CODE_VAL    VARCHAR(10)     NOT NULL,
    LANG_DIV_VAL    VARCHAR(10)     NOT NULL,
    LANG_CONTENT    VARCHAR(500)    NOT NULL,
    REMARK_CONTENT  VARCHAR(500),
    REG_USER_ID     VARCHAR(50),
    REG_DATETIME    TIMESTAMP,
    UPDATER_ID      VARCHAR(50),
    UPDATE_DATETIME TIMESTAMP,
    CONSTRAINT PK_MLG_DETAIL PRIMARY KEY (MLG_DETAIL_ID),
    CONSTRAINT FK_MLG_DETAIL_GROUP FOREIGN KEY (MLG_CODE_VAL) REFERENCES TB_MLG_GROUP (MLG_CODE_VAL),
    CONSTRAINT UK_MLG_DETAIL UNIQUE (MLG_CODE_VAL, LANG_DIV_VAL)
);

COMMENT ON TABLE TB_MLG_DETAIL IS '다국어 상세';
COMMENT ON COLUMN TB_MLG_DETAIL.MLG_DETAIL_ID IS '다국어 상세 ID';
COMMENT ON COLUMN TB_MLG_DETAIL.MLG_CODE_VAL IS '다국어 코드값';
COMMENT ON COLUMN TB_MLG_DETAIL.LANG_DIV_VAL IS '언어 구분값';
COMMENT ON COLUMN TB_MLG_DETAIL.LANG_CONTENT IS '언어 내용';
COMMENT ON COLUMN TB_MLG_DETAIL.REMARK_CONTENT IS '비고';
COMMENT ON COLUMN TB_MLG_DETAIL.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN TB_MLG_DETAIL.REG_DATETIME IS '등록 일시';
COMMENT ON COLUMN TB_MLG_DETAIL.UPDATER_ID IS '수정자 ID';
COMMENT ON COLUMN TB_MLG_DETAIL.UPDATE_DATETIME IS '수정 일시';
